### ISSUE TITLE
The CNC mount stp does not reflects the current state

### ISSUE THREAD

**Issue by testack18** [Cartographer3D/cartographer-probe#3]
Actually I do not moved my X limit switch and the CNC mount for cartographer does not reach the X limit switch. I wanted to design something like the CNC tap has on their Chaoticlab's github: https://github.com/Chaoticlab/CNC-Tap-for-Voron/blob/master/STL/XY_Switch_Adapter/CNC_Voron_TAP_XY_Switch_Adapter_V2.stl
But the CNC mount file is not representing the actual one I ordered from Cartographer so its hard to design my own Switch adapter.

Could you please update the CNC mount stp file to reflect the real mount?

**Comment by RichardTHF** [comment]
Fixed, sorry we made itteration changes about a month ago and i forgot to update. 

Doing now.
